name: prismlauncher
license: GPL-3.0-only
base: core22
website: https://prismlauncher.org/
source-code: https://github.com/PrismLauncher/PrismLauncher
issues: https://github.com/PrismLauncher/PrismLauncher/issues
donation: https://opencollective.com/prismlauncher
contact: https://discord.gg/prismlauncher
summary: A custom Minecraft launcher with modpack support
adopt-info: prismlauncher

grade: devel
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64

parts:
  prismlauncher:
    source: https://github.com/PrismLauncher/PrismLauncher.git
    source-tag: "9.0"
    parse-info:
      - usr/share/metainfo/org.prismlauncher.PrismLauncher.metainfo.xml
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - "-DCMAKE_INSTALL_PREFIX=/usr"
      - "-DCMAKE_BUILD_TYPE=RelWithDebInfo"
      - "-DENABLE_LTO=ON"
      - "-DLauncher_BUILD_PLATFORM=snap"
      - "-DLauncher_QT_VERSION_MAJOR='5'"
    override-pull: |
      craftctl default
      # Fix the icon reference in the desktop file
      sed -i.bak -e 's|Icon=org.prismlauncher.PrismLauncher|Icon=/usr/share/icons/hicolor/scalable/apps/org.prismlauncher.PrismLauncher.svg|g' program_info/org.prismlauncher.PrismLauncher.desktop.in
      # Remove the build directory so that local development doesn't interfere with Snap compilation
      rm -rf build
      git submodule update --init --recursive
    build-packages:
      - zlib1g-dev
      - openjdk-17-jdk
      - scdoc
      - libgl1-mesa-dev
      - extra-cmake-modules
    build-snaps:
      - kf5-5-106-qt-5-15-9-core22
      - kf5-5-106-qt-5-15-9-core22-sdk
    stage-packages:
      - openjdk-21-jre
      - openjdk-17-jre
      - openjdk-8-jre

apps:
  prismlauncher:
    common-id: org.prismlauncher.PrismLauncher
    desktop: usr/share/applications/org.prismlauncher.PrismLauncher.desktop
    command: usr/bin/prismlauncher
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - audio-playback
